### ISSUE TITLE
Investigate performance of acquisition optimizer

### ISSUE THREAD

**Issue by joelberkeley** [secondmind-labs/trieste#117]
As a user, I want the acquisition optimizer to be as efficient as possible. We currently use gpflow's Scipy optimizer with tfp's bijector for bounds. However, @joelberkeley has found in #74 that tfp's `lbfgs_minimize` takes fewer steps (though each of those steps take longer). We may alternatively be able to use gpflow's Scipy with bounds since it is L-BFGS-B. This may be faster than using the tfp bijector.

Task is to investigate the performance impact of each option and implement the "best" (having decided what "best" means).

**Comment by joelberkeley** [comment]
[this paper](https://arxiv.org/abs/2012.08240) studies optimization performance for acquisition functions

**Comment by uri-granta** [comment]
Addressed in https://github.com/secondmind-labs/trieste/pull/438 (and elsewhere)
