### ISSUE TITLE
Batch Bayesian Optimization available?

### ISSUE THREAD

**Issue by rzc331** [secondmind-labs/trieste#119]
Hi, I can find some keywords matching "BatchAcquisitionFunction" in the API reference, but see no batch BO related things in the tutorials. Wondering if batch BO is supported by this package?
I am a beginner and I'd appreciate it if anyone could reply. 
Thanks in advance!

**Comment by joelberkeley** [comment]
Hi @rzc331, thanks for your question. Yes trieste does support batch BO via that the [ `BatchAcquisitionRule`](https://secondmind-labs.github.io/trieste/autoapi/trieste/acquisition/rule/index.html#trieste.acquisition.rule.BatchAcquisitionRule) and [`BatchAcquisitionFunction`](https://secondmind-labs.github.io/trieste/autoapi/trieste/acquisition/index.html#trieste.acquisition.BatchAcquisitionFunctionBuilder), though we have not yet implemented any batch acquisition functions.

We are currently working on adding a batch sampler using the reparametrization trick, akin to the [`IndependentReparametrizationSampler`](https://secondmind-labs.github.io/trieste/autoapi/trieste/acquisition/index.html#trieste.acquisition.IndependentReparametrizationSampler). Once we have done that, we will add an implementation for batch EI and tutorials for batch BO

Let me know if you have any further questions

**Comment by rzc331** [comment]
This is excellent!
Looking forward to this feature!

**Comment by joelberkeley** [comment]
Great to hear. Unless you have further questions I'll close this issue

**Comment by joelberkeley** [comment]
By the way, a good place to ask questions like this is the slack workspace. There's a link for that in the project README

**Comment by joelberkeley** [comment]
@rzc331 hi, we've now merged a batch monte-carlo based sampler and the batch expected improvement acquisition function. We're also working on documentation for batch BO. These will remain on the develop branch until the next release, which we hope to do in the next two weeks or so

**Comment by rzc331** [comment]
Wow! That's really great news!
I am looking forward to that, thank you! @joelberkeley

**Comment by joelberkeley-secondmind** [comment]
@rzc331 trieste 0.4.0 is now out. The batch-sequential BO tutorials are now in (they're sections in two existing tutorials) and available on the [tutorials page](https://secondmind-labs.github.io/trieste/tutorials.html). This is also all now available in a pip-installable release

**Comment by rzc331** [comment]
Yeah, I see this fantastic sections in the tutorial, looks really neat and easy to use!

Thanks again!

**Comment by rzc331** [comment]
Can I ask why does the size of the tensor would blow up in Batch EI?

I only have a 4-dimension search space containing 270 discrete points. When I use the default parameters with sample_size=1000 & num_query_points=3, it would generate a tensor with shape[19683000,3,3]

Output error message:
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[19683000,3,3] and type double on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Mul]

Reducing the num_query_points to less than 3 would work but it's not really a batchwise way. Reducing sample_size will give the same error.

Got stuck here for quite some time, I would appreciate it if anyone could advice!

**Comment by joelberkeley** [comment]
Hi. Do you mind asking this in a new ticket?
