### ISSUE TITLE
Check end-to-end support for multi-output models

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [secondmind-labs/trieste#121]
**Describe the feature you'd like**
As a user, I'd like to be confident I can use a multi-output model with trieste in a complete BO loop, without having to use any hacks. As a maintainer, I'd like to know users can do this.

**Describe alternatives you've considered**
Either write a test, notebook (perhaps duplicate an existing notebook to show an alternative approach), or both.

**Additional context**
victor's notes

> it probably does but this is worth checking. In particular:
> - does the model update work?
> - does the data update work?
> maybe this PR is about writing a unit test?

**Comment by uri-granta** [comment]
The multi-objective tutorial and the `test_multi_objective_bayesian_optimization` integration tests both have full loops using multi-output models.
