### ISSUE TITLE
Infinite lazy collection (generator) of results

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [secondmind-labs/trieste#123]
As a user, I want more a more composable central optimizer, so I can customize various aspects of the main BO loop.

To this end, I suggest `optimize` return an infinite generator of results.

For example
* I can choose why and when to stop the loop
```python3
for res in optimize(...):
    if res.data.observation < some_minimum_required_value:
        return res
```
* I can resume the loop without a new call to `optimize` (reducing typing, along with the chance for mistakes)
```python3
results = optimize(...)
first5 = itertools.islice(results, 5)
# I examine first5 and decide I want more
next3 = itertools.islice(results, 3)
```
  * I get logging for free

**Comment by joelberkeley-secondmind** [comment]
this may even provide ask-tell for free if we use generator's `.send(...)`

**Comment by joelberkeley-secondmind** [comment]
What I meant to add, is that this can be achieved with an infinite generator
```python
def optimize(...)
    while True:
        points = rule.acquire(...)
        yield points
        # update data and models
```

**Comment by uri-granta** [comment]
We've essentially implemented this via the early_stop_callback argument for optimize (https://github.com/secondmind-labs/trieste/pull/579) as well as ask tell.
