### ISSUE TITLE
Add method to recover optimization from failed step

### ISSUE THREAD

**Issue by joelberkeley** [secondmind-labs/trieste#124]
**Describe the feature you'd like**
As a user, I want to be able to **easily** recover the optimization process from a failed step. Based on the relevant notebook, the following API may be a good approach
```python
class BayesianOptimizer:
    ...
    def recover(
        self, total_steps: int, history: List[Record[S]], acquisition_rule[S, SP]
    ) -> OptimizationResult[S]:
       result, new_history = self.optimize(
            total_steps - len(history),
            history[-1].datasets,
            history[-1].models,
            acquisition_rule,
            history[-1].acquisition_state
       )
       return OptimizationResult(result, history + new_history)
```
though we may wish to be able to substitute in a new model/state if desired

**Comment by uri-granta** [comment]
I think a cleaner way of doing this would be to add an optional `history` argument to `optimize`, which if present gets appended to and used to calculate the number of remaining steps. This avoid duplicating what is already a very complex interface.

**Comment by uri-granta** [comment]
Actually that would involve having to explicitly pass in models and data, which can be extracted from the history. Still, it would be a pain to add a `recover` method for each of the 10 overloads of optimize :-(
