### ISSUE TITLE
Scaling `Dataset.observations` in each BO iterations 

### ISSUE THREAD

**Issue by TsingQAQ** [secondmind-labs/trieste#125]
**Describe the feature you'd like**
For some optimization process (e.g., multi-objective optimization), a scaling/transforming/normalization of each objective from R-> [0, 1] is preferred or even a necessary step (This is not for easier gp modeling but for instance, to make each objective function equivalent important for later operation). Usually this could be done for instance by just scaling `Dataset.observations` to [0, 1] (and then build the `ProbabilisticModel`). While seems I cannot think of an easy way to do in Trieste with minor effort. 

One way I can think of is just scaling data in `create_bo_model` before build of the gp,  but since the observer still receives raw data, the inner loop in `BayesianOptimizer` is not scaled properly as can be seen [here](https://github.com/secondmind-labs/trieste/blob/9fb9ea7ae9ae4f9686a96fdf57fc96b8ee7dd3f7/trieste/bayesian_optimizer.py#L249-L256).

**Describe alternatives you've considered**
- Scale inside `observer`: dynamically update scaling is not very possible as earlier data in model will not get updated due to the augmentation style of data.
- Scale GP predictions according to data: not very sure if this is mathematically equivalent when consider mean and variance, also one needs to pass the scaling coefficient deeply into the `_acquisition_function` to consider this type of operation.

**Comment by joelberkeley-secondmind** [comment]
thanks for a detailed github issue. In order to avoid retraining the model on every step (as @vpicheny pointed out), you'd need to train the model on unscaled data. Do you agree?

**Comment by TsingQAQ** [comment]
thanks for the comment! Actually am not very sure about why should avoid retraining the model per step, if that means to achieve for instance retraining the model every 5 bo iteration then train the model on unscaled data is indeed preferable. 

-----------------------
Maybe allow me clarify the issue a bit to make it more clear. There is no problem in current `bayesian_optimizer`, the feature request is just for some methods, especially in multi-objective setting, the optimization is performed with an expectation that all the objective function value ranges in the same scale, like [0, 1], for instance see the description of *Synthetic six-objective function* (Sec 5) in [this paper](https://arxiv.org/pdf/1805.12168.pdf):

"_we linearly transform the objectives values to [0, 1] for simplicity_"

As if one objective function value ranges from [-1e3, 0] and the other range [0, 1], a scaling might be necessary to make them all roughly in [0, 1] (and the do some operation, like scalarize different objective functions).  Since the real objective function ranges not known before hand, we can scale based on the data we have per 1 or several iterations. While this scaling seems not very easy to handle in Trieste.

**Comment by joelberkeley-secondmind** [comment]
is common [0, 1] scaling beneficial when optimizing the model, finding the new point via the acquisition rule, or both?

**Comment by joelberkeley** [comment]
could you do this as follows
```python
class YourBuilder(AcquisitionFunctionBuilder):
    def prepare_acquisition_function(data, model):
        rescaled_observations = rescale(data.observations)
        def acquisition_function(at):
            ...  # do stuff with rescaled observations
        return acquisition_function
```

**Comment by TsingQAQ** [comment]
Thanks, yes this is indeed something doable, though if I understood correctly, one have to re-modify the acquisition function here accordingly as having to handle the unscaled `model`.

Maybe if it is okay we can close this issue atm and wait for some specific problem, as it seems a bit hard to discuss why there is a need without a concrete example. Seems this feature is not necessary but only for some multi-objective method.
