### ISSUE TITLE
 Notebook explaining what BO is and how it works

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [secondmind-labs/trieste#129]
As a user new to Bayesian optimization, I would like a notebook that explains what Bayesian optimization is and how it works, so I can start using it to solve my optimization problems with little experience.

As a maintainer, I want the above so that people with little experience of BO use the project as well as those with lots of experience, thus promoting a larger community.

**Comment by uri-granta** [comment]
The expected improvement tutorial essentially does this (which will be made more clear following https://github.com/secondmind-labs/trieste/pull/769). It could definitely use improvement, but this is covered by https://github.com/secondmind-labs/trieste/issues/472.
