### ISSUE TITLE
Allow BatchReparametrizationSampler to use multiple batch sizes

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [secondmind-labs/trieste#132]
As a maintainer, I want users to be able to use a single `BatchReparametrizationSampler` with multiple batch sizes, so that they have as much flexibility as possible.

This may be possible by extending the current eps with new N(0, 1) samples if the batch size increases, or take a subsample if it decreases, thus ensuring that eps will remain fixed _for any given batch size_.

**Comment by uri-granta** [comment]
Samplers can be used with different batch sizes but only after calling reset_sampler. Our current approach where batch size is inferred the first time afterwards is sufficient given our current sampler architecture.
