### ISSUE TITLE
Automatic link references in documentation

### ISSUE THREAD

**Issue by joelberkeley** [secondmind-labs/trieste#134]
As a maintainer, I want to be able to write docs with minimal effort.

As a user, I want all links/cross-references in the docs to be accurate so that I know what everything means and I can trust the docs.

In this regard, @st-- has suggested adding a Sphinx [`default_role`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html) of ["any"](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-any). This would create links where it can from doc entries like ``foo``, raising a warning where a link can't be found, or where there are multiple possible targets. To add this, we'd need to
  - change all links that should only be formatted as code to use double backticks, so as to avoid links where there isn't meant to be one
  - fix all doc build warnings

This was originally proposed in #131, which includes a number of comments

**Comment by uri-granta** [comment]
Not worthwhile in my opinion for a few reasons:

1. would require fixing around 500 warnings, which will take a while
2. people will inevitably forget to use double-backticks in new docstrings, and time-wasting docstring errors are at the moment a bigger issue than missing doc links
3. has the potential to overlink and pollute the docs with incorrect links

Recommend closing and continuing to use explicit links.
