### ISSUE TITLE
Change acquisition function builders to be functions

### ISSUE THREAD

**Issue by joelberkeley** [secondmind-labs/trieste#137]
As a maintainer/user, I want the acquisition function builders to be lightweight: easy to compose, construct and generally manipulate, so that code is easier to read, conceptualise and extend.

To this end, I propose changing the acquisition function builders to be functions not classes. For example:
```python
AcquisitionFunctionBuilder = Callable[
    [Mapping[str, Dataset], Mapping[str, ProbabilisticModel]], AcquisitionFunction
]


def expected_improvement(
    data: Mapping[str, Dataset], models: Mapping[str, ProbabilisticModel]
) -> AcquisitionFunction:
    ...
```
If it's not clear to users what is and isn't an acquisition function builder by its signature, we could either take care to say what is an `AcquisitionFunctionBuilder` in the docstring for each one, or do the following workaround:
```python
def _expected_improvement(
    data: Mapping[str, Dataset], models: Mapping[str, ProbabilisticModel]
) -> AcquisitionFunction:
    ...

expected_improvement: Final[AcquisitionFunctionBuilder] = _expected_improvement
```
This would obviously not be needed for e.g.
```python
def probability_of_feasbility(threshold: TensorType) -> AcquisitionFunctionBuilder:
    ...
```
which returns a builder, rather than is one. It appears this would show up clearly in the docs. It may also be clearer to put everything on the same footing and have them all return builders:
```python
def expected_improvement() -> AcquisitionFunctionBuilder:
```

**Comment by uri-granta** [comment]
This is no longer plausible as AcquisitionFunctionBuilder now also includes the logic for updating functions without retracing. (In fact, it's likely that a better solution would have been to remove AcquisitionFunctionBuilders altogether and just use an AcquisitionFunction class that handles updates itself, but at this point this looks like far too much work: https://github.com/secondmind-labs/trieste/pull/650/.)
