### ISSUE TITLE
EI uses model variance where it should use stddev

### ISSUE THREAD

**Issue by awav** [secondmind-labs/trieste#150]
https://github.com/secondmind-labs/trieste/blob/0e8f34e87b9e1a0ec2ea6fd2fd857eff49c202ab/trieste/acquisition/function.py#L154

I believe $EI(x) = (f - \mu_x)\Phi(\frac{f - \mu_x}{\sigma_x}) + \sigma_x \phi(\frac{f - \mu_x}{\sigma_x})$, but for some reason Trieste uses \sigma_x^2 instead.

**Comment by joelberkeley** [comment]
the tfp Normal on the line above is wrt to the model mean and stddev, rather than 0 and 1. I'm just working out how that applies. Here's the full function
```python
def expected_improvement(model: ProbabilisticModel, eta: tf.Tensor, at: TensorType) -> tf.Tensor:
    mean, variance = model.predict(at)
    normal = tfp.distributions.Normal(mean, tf.sqrt(variance))
    return (eta - mean) * normal.cdf(eta) + variance * normal.prob(eta)
```

**Comment by joelberkeley** [comment]
I think it's right, here's why:

sigma * phi((eta - mean) / sigma ; 0, 1)  # [this paper](https://arxiv.org/pdf/1807.02811.pdf)
sigma ** 2 * phi(eta ; mean, sigma)  # trieste

The exponential contributions, using the [tfp docs](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Normal#prob), are ((eta - mean) / sigma) ** 2 and (eta - mean) ** 2 / sigma ** 2
The rest is sigma * 1 / 1 and sigma ** 2 * 1 / sigma

Reopen this if you think I've made a mistake
