### ISSUE TITLE
Include explanations in both acquisition function and builder docs

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [secondmind-labs/trieste#156]
As a user, I want to be able to see the docs easily from both the acquisition functions and their builders, in the built docs and the hints that appear in jupyter notebooks, so that I know which function does what.

**Comment by uri-granta** [comment]
Builders now typically return class instances with their own docs. (Also the actual acquisition function is rarely visible to the user anyway, typically hiding behind the acquisition rule.)
