### ISSUE TITLE
model sample has inconsistent shapes

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [secondmind-labs/trieste#157]
Various docs and implementations for model `sample` methods disagree. They need to be consistent across
  - docs for ProbabilisticModel.sample
  - implementations in the GPflow wrappers
  - the model test utility
  - the assumed shape for the `.sample()` call in `ThompsonSampling`

and maybe others. These should also be consistent with the reparametrization samplers.

The first task is to choose appropriate shapes.

**Comment by joelberkeley-secondmind** [comment]
suggestion is to remove `.sample` from `ProbabilisticModel`, and use reparam samplers in thompson sampling rule

**Comment by uri-granta** [comment]
The various sample methods are now consistently shaped, taking query points of shape [..., N, D] and returning samples of shape [..., S, N, E].
