### ISSUE TITLE
Enable ProbabilisticModel implementations without .sample()

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [secondmind-labs/trieste#158]
As a user, I want to be able to define a `ProbabilisticModel` without a `sample` implementation, so that I don't need to write one if I'm not using it (which given no acquisition functions do, is pretty likely).

One approach to this is to simply remove the sample method and let users define one if they want it. For the GPflow wrappers, we can then simply either use one of trieste's reparametrization samplers or GPflow's `sample_mvn`

**Comment by joelberkeley-secondmind** [comment]
related to #157

**Comment by joelberkeley-secondmind** [comment]
see also this discussion which would help achieve this https://github.com/secondmind-labs/trieste/discussions/145

**Comment by uri-granta** [comment]
We could make the sample method non abstract but still non implemented, like predict_y. However, I think the absence of a sample method should be an active choice as it is very unusual, so the current approach — where the user has to implement sample but can just have it raise a NotImplementedError — is preferable.
