### ISSUE TITLE
Improve predict performance by caching expensive results

### ISSUE THREAD

**Issue by joelberkeley** [secondmind-labs/trieste#160]
**Describe the feature you'd like**
As a user, I want the models to avoid recomputing expensive results on every prediction, when those results don't change, so that calling predict multiple times is efficient.

**Is your feature request related to a problem? Please describe.**
The acquisition optimizer can make repeated calls to a model's predict. This can involve taking the cholesky of the covariance matrix wrt the training data. Since this value is fixed for a given step, we can cache the result to improve performance.

**Describe alternatives you've considered**
It's _possible_ this optimization should be in the acquisition optimizer itself, but it seems unlikely since
- it's applicable anywhere `predict` is called
- the implementation and performance benefit will likely depend on the type of model (e.g. NNs involve no cholesky)

**Comment by uri-granta** [comment]
I believe this is now handled for the gpflow models by generating and updating a posterior cache (#523 et al).
