### ISSUE TITLE
More space-filling sampling method than tf.uniform 

### ISSUE THREAD

**Issue by satrialoka** [secondmind-labs/trieste#175]
**Describe the feature you'd like**

In the `Box` class the sampling method is `tf.random.uniform`. I found it less space-filling than for example 
`tf.math.sobol_sample`. This will make the metamodel better approximate the function at the initial phase of optimization. it might be good if the user can choose what kind of sampler to use in the `Box` class. 
as a comparison, botorch had a set of samplers we can select ([link](https://botorch.org/api/sampling.html)) and in the GPflowOpt we have `Design` class ([link](https://github.com/GPflow/GPflowOpt/blob/master/gpflowopt/design.py)) . 

**Additional context**
to give some context what's available there: [link](https://como.ceb.cam.ac.uk/media/preprints/c4e-Preprint-182.pdf)

**Comment by joelberkeley** [comment]
I assume you're particularly looking at how the space is used in the acquisition optimizer. If so, it may also be good to let users customize the acquisition optimizer (which would indirectly allow users to customize the sampling in the optimizer, depending on how that's done). This is something we intend to do anyway

**Comment by satrialoka** [comment]
yes. additionally, it might be good to have that sampling customization for generating initial data before the optimization iteration.

**Comment by satrialoka** [comment]
I have the custom sampler for the initial DoE at the moment. I added a [Design class ](https://github.com/satrialoka/trieste/commit/88a6f02050530df077516d775fadf8d7f57219b9#diff-b491084d9dee913da25dc734df837ed88169ba70299461477fc4c20640aae52c) for customizing the sampler/DoE method. Haven't check how it will interact with the optimizer though. The demo can be checked at [link](https://github.com/satrialoka/trieste/blob/custom-sampling/docs/notebooks/custom_sampler.pct.py). What do you think? @henrymoss 

for the Latin Hypercube Design, we have NumPy implementation in UGhent internal repo, If the current way to incorporate the custom sampler is ok for you, I can port it to TensorFlow. Or do you have another idea?

**Comment by henrymoss** [comment]
That looks great! I'm happy with the Sobol/Halton. Do you feel that the LHD is needed?

**Comment by satrialoka** [comment]
personally, I wouldn't include the LHD and stick with Sobol/Halton. Some BO library also doesn't have the LHD. If the user wants LHD, it can be implemented by using the Design class.

**Comment by henrymoss** [comment]
Perfect. Are you happy to do a full PR with this functionality?

**Comment by satrialoka** [comment]
Okay :ok_hand:
