### ISSUE TITLE
Acquisition functions are being retraced

### ISSUE THREAD

**Issue by joelberkeley** [secondmind-labs/trieste#178]
**Describe the bug**
TensorFlow is emitting retracing warnings for qEI with the batch acquisition rule. This means function compilation is not working and the code will be slower.

**To reproduce**
Add qEI with the batch rule to the integration tests, run and look at the logs.
```python
    ...
    (30, BatchAcquisitionRule(3, BatchMonteCarloExpectedImprovement(1000).using(OBJECTIVE))
    ...
```

**Expected behaviour**
Tracing should happen just once.

**System information**
 - OS: Ubuntu 20.04
 - Python version: 3.8
 - Trieste version: 92e6e51bb218e2215f93cf3994b4ce9d8a4743dc
 - TensorFlow version: 2.3.1
 - GPflow version: 2.1.1

**Comment by joelberkeley-secondmind** [comment]
most important question: are they being retraced every call or on every step?

**Comment by uri-granta** [comment]
This has now been fixed (in multiple PRs including https://github.com/secondmind-labs/trieste/pull/340 which specifically covers BatchMonteCarloExpectedImprovement)
