### ISSUE TITLE
Support tuples as bounds in Box constructor

### ISSUE THREAD

**Issue by satrialoka** [secondmind-labs/trieste#212]
**Describe the bug**
When I use a `tuple` to define the bounds of the `Box`,  i got `tf.float32` instead of `tf.float64` tensor when sampling from it.

**To reproduce**
Steps to reproduce the behaviour:
1. define the bound of `Box` using `tuple` instead of `list`
2. call `.sample(number_of_sample)`

Include a minimal reproducible code example if relevant.
```
import tensorflow as tf
import trieste as tr

bound_list = tr.space.Box([0., 0.], [1., 1.])
bound_tuple = tr.space.Box((0., 0.), (1., 1.))

tf.debugging.assert_type(bound_tuple.sample(5),bound_list.sample(5).dtype)
```
**Expected behaviour**
I expect the tensor type to be `tf.float64`, or at least there is a defensive code to inform the user that the bound should be `list` instead of `tuple`.

**System information**
 - OS: Windows 10
 - Python version: 3.8.6
 - Trieste version: 0.4.0
 - TensorFlow version: 2.4.0
 - GPflow version: 2.1.4

**Additional context**
The fix could be defining the `dtype=tf.float64` when calling `tf.convert_to_tensor` [here](https://github.com/secondmind-labs/trieste/blob/5db2b0af0cc9ff6fd4b1f4602fcad526c6e61be7/trieste/space.py#L202) or write defensive code to only accept `list` as an input.

**Comment by joelberkeley** [comment]
In trieste we assume the types as they are annotated. For `Box` these are `list[int]` and `TensorType`. It would be impractical to assert these everywhere (and result in duplication which is prone to errors). That said, unfortunately mypy wouldn't catch passing a `tuple` as `tf.Tensor` is untyped, for now at least.

As such, this isn't a bug, but we can make it a feature request.

**Comment by satrialoka** [comment]
Ah, I see. would be nice if mypy be able to catch this.

**Comment by joelberkeley** [comment]
yeah - numpy 1.12 has type hints, and tensorflow's working on them, but that's taking a while

**Comment by uri-granta** [comment]
This has now been fixed in develop: you can now pass in arbitrary "tensor-like" bounds (nested sequences of floats) including tuples as well as lists.
