### ISSUE TITLE
Add ask-tell optimizer

### ISSUE THREAD

**Issue by joelberkeley** [secondmind-labs/trieste#215]
**Describe the feature you'd like**
As a user, I'd like an ask-tell optimizer so that ...

**Comment by joelberkeley** [comment]
This could use coroutines (they seem to be a python core feature designed for this use case). For example
```python
def optimize(
    search_space: SP,
    datasets: Mapping[str, Dataset],
    models: Mapping[str, TrainableProbabilisticModel],
    acquisition_rule: AcquisitionRule[S, SP],
    acquisition_state: Optional[S] = None,
) -> Generator[Result[TensorType], Mapping[str, Dataset], None]:
    while True:
        try:
            query_points, acquisition_state = acquisition_rule.acquire(
                search_space, datasets, models, acquisition_state
            )

            observer_output = yield Ok(query_points)

            datasets = {tag: datasets[tag] + observer_output[tag] for tag in observer_output}

            for tag, model in models.items():
                dataset = datasets[tag]
                model.update(dataset)
                model.optimize(dataset)
        except Exception as e:
            yield Err(e)  # todo is this right?
```
used like
```python
ask_tell = optimize(search_space, initial_data, models, EfficientGlobalOptimization())
new_point = next(ask_tell)

if new_point.is_ok:
    new_data = observer(new_point.unwrap())
    new_point = ask_tell.send(new_data)
```

**Comment by satrialoka** [comment]
I have tried above example for non-async case, and it was pretty nice. 
regarding the function naming, Isn't it more natural for using the ask/tell name itself rather than the default python's coroutine function name? for example `next(ask_tell)` could be modified as `ask_tell.ask()`, `ask_tell.send(new_data)` could be `ask_tell.tell(new_data)`.

**Comment by joelberkeley** [comment]
@satrialoka re `.ask()` and `.tell()`, possibly, but you'd have to ask if it's worth wrapping it for the different names. Wrapping it may lose out on certain aspects of coroutines, and it would of course imply a little extra maintenance. I don't know the answer.

**Comment by satrialoka** [comment]
ah yea, you're right.  maybe @uri-granta has a comment on this?

**Comment by uri-granta** [comment]
Keeping the optimizers as bare coroutines (as opposed to a wrapped class) is attractive to me too, but there's no reason we can't also define standalone `ask` and `tell` functions right?

```python
AskTellOptimizer = Generator[Result[TensorType], Mapping[str, Dataset], None]

def ask(ask_tell: AskTellOptimizer) -> Result[TensorType]:
    return next(ask_tell)
def tell(ask_tell: AskTellOptimizer, new_data: Mapping[str, Dataset]) -> Result[TensorType]:
    return ask_tell.send(new_data)

ask_tell = optimize(search_space, initial_data, models, EfficientGlobalOptimization())
new_point = ask(ask_tell)

if new_point.is_ok:
    new_data = observer(new_point.unwrap())
    new_point = tell(ask_tell, new_data)
```

**Comment by satrialoka** [comment]
looks nice for me

**Comment by henrymoss** [comment]
I wonder if this approach could be even more general. So allow the passing of a trained model, rather than just the data. 

This could be useful for very complicated pipelines / use-cases where models are to maintained (and efficiently) updated elsewhere?

**Comment by joelberkeley** [comment]
there's not a lot in the `optimize` function, so you have to ask at what point is it worth users just writing their own function rather than adding functionality to this one?

**Comment by apaleyes** [comment]
While implementing optimize as iterator is nice looking as far as Python syntax goes, I wander how useful that would be.

Pro is that it will allow us to use Trieste in all kinds of iteration scenarios, for example with itertools package. But it feels that if you are able to generate a sequence of interim optimization steps, then you can express your objective function in Python anyway. If that is so, why not let Trieste run the whole optimization loop?

Ask/tell is most useful if you literally have to freeze the optimizer state (perhaps even serialize it), go away, evaluate the objective (say [3D print a part](https://arxiv.org/abs/2107.12809)), come back, feed in the evaluation results. `optimizer.ask()` and `optimizer.tell()` seem more natural in that scenario. Besides, if we ever want to consider serializing optimizer, serializing `yield` state [is tricky](https://news.ycombinator.com/item?id=1010533).

Both functions, especially ask, shall also support optional parameters, e.g. number of points in the batch, but I guess that can be supported with any approach.

I could be overcomplicating this though. Thoughts?

**Comment by apaleyes** [comment]
This issue can be probably closed now
