### ISSUE TITLE
pylint is not run as part of the build process

### ISSUE THREAD

**Issue by johnamcleod** [secondmind-labs/trieste#260]
**Describe the bug**
At the moment pylint is not run as part of the build process. As such, the responsibility of ensuring that the linting checks pass is left to individuals, and it is possible to merge code into develop which fails these checks.

**To reproduce**
At the time of writing there are four places where the checks fail when run on the `develop` branch.

`pytest --pylint --cache-clear -m pylint -v trieste`

These are the failures:
=============================================FAILURES==============================================
_____________________________ [pylint] trieste/acquisition/optimizer.py _____________________________
C:152, 0: Missing function or method docstring (missing-function-docstring)
_______________________________ [pylint] trieste/acquisition/rule.py ________________________________
W:203,16: Unused variable 'i' (unused-variable)
______________________________ [pylint] trieste/acquisition/sampler.py ______________________________
W:221, 4: Parameters differ from overridden 'sample' method (arguments-differ)
____________________________ [pylint] trieste/models/model_interfaces.py ____________________________
W:438, 4: Parameters differ from overridden 'update' method (arguments-differ)

**Expected behaviour**
On develop these checks should pass.

**Comment by johnamcleod** [comment]
It looks like two of these failures are being addressed as part of #258.

**Comment by uri-granta** [comment]
This is known. Trieste uses flake8 rather than pylint for linting. The pylint config and task that I added to pyproject.toml was merely to compare what sort of errors flake8 was picking up compared to pylint. The idea in the long term is to improve flake8 so it catches everything we care about, and only introduce pylint if we can't do that.

**Comment by hstojic** [comment]
@uri-granta this seems like it should be closed then?
