### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by henrymoss** [secondmind-labs/trieste#279]
Have one file full of global params that can be controlled by the user for a specific BO run. Example parameters include:

- num acq optimization restarts
- type of optimizer
- number of model optimizer resarts

**Comment by joelberkeley** [comment]
fyi global mutables are not advisable. a config object you pass to the optimizer is an alternative

**Comment by henrymoss** [comment]
Yep makes sense. So similar to some kwargs to the optimzer?

**Comment by joelberkeley** [comment]
indeed

**Comment by henrymoss** [comment]
We currently have some hacks where we set "magic" numbers in the code (e.g. line 439 of https://github.com/secondmind-labs/trieste/blob/develop/trieste/models/model_interfaces.py)

**Comment by henrymoss** [comment]
I thought having a config file might be a good way to choose these.

**Comment by joelberkeley** [comment]
you could pass those parameters as optional parameters at class initialization. Would that be practical?

**Comment by uri-granta** [comment]
Closing as this is really about how best to run experiments which is covered by another issue.
