### ISSUE TITLE
Plotting utilities

### ISSUE THREAD

**Issue by joelberkeley** [secondmind-labs/trieste#29]
As a researcher, I would like plotting utilities available for effortlessly plotting observer data, posteriors, acquisition functions and perhaps other things over search spaces, so that I can quickly and easily analyse Bayesian optimization progress.

It may be best to start simple, with tools only for two dimensional input spaces (or one dimensional if they're more common)

There are lots of examples of plotting in the notebooks. These will need updating to make use of this new functionality, and the unused plotting functionality in the notebooks utils removed

**Comment by uri-granta** [comment]
Plotting utilities are currently available in trieste.experimental (though they could be improved and better tested in future).
