### ISSUE TITLE
Incorrect covariance_between_points for SGPR

### ISSUE THREAD

**Issue by sebastianober** [secondmind-labs/trieste#329]
**Describe the bug**
In trieste/models/model_interfaces.py, the `covariance_between_points` method of the `GaussianProcessRegression` class uses the full GP covariance, even when the model is SGPR. 

**To reproduce**
N/A

**Expected behaviour**
When SGPR is used as the internal model, `covariance_between_points` should return the covariance computed using the sparse approximation in SGPR (http://proceedings.mlr.press/v5/titsias09a.html).

**System information**
N/A

**Additional information**
The predictive covariance is written in closed form in Eq. 4 of http://proceedings.mlr.press/v139/artemev21a.html. A reference implementation can be found in `predict_f` in the GPflow implementation: https://gpflow.readthedocs.io/en/master/_modules/gpflow/models/sgpr.html#SGPR

**Comment by uri-granta** [comment]
Fixed in #531
