### ISSUE TITLE
change how we make deep copies of models 

### ISSUE THREAD

**Issue by hstojic** [secondmind-labs/trieste#335]
given that we are moving to supporting other model types than GPflow, we'll probably need to rethink how we make deep copies of the models in each iteration, perhaps the top interface (e.g. `ProbabilisticModel`) should require that each model type should implement some kind of `save_model` method that `BayesianOptimizer` would call, since different model types might do it differently (e.g. for Keras networks data does not need to be saved, only the architecture and weights) - then interface of each model type (e.g. `GPflowPredictor`) would actually define the save method.

any thoughts?
@joelberkeley perhap? you have written the current `module_deepcopy` function, right?

**Comment by joelberkeley** [comment]
`deepcopy(...)` can be customized for each class with the special method `__deepcopy__`. This method is optional (you can `deepcopy` an object without it), so I chose not to demand it on `ProbabilisticModel`. `module_deepcopy` is simply a convenience function to make it easy for people to implement `__deepcopy__` for certain (problematic) model structures

**Comment by hstojic** [comment]
thanks @joelberkeley, that clarifies things, if needed we use the `__deepcopy__` method to modify it then
additional clarification questions: 
- the main usage is to have access to a complete model after each iteration in the BO loop - for diagnostics, recovering from errors etc, right?
- what about memory footprint? GPflow models contain data, hopefully data is not really copied for each deepcopy, in case of large datasets with SVGP that could be a lot...

that issue with deepcopying `tf.Module` has been fixed in TF probability 0.12 and we are now on `tensorflow-probability>=0.12`, so we should be able to remove `module_deepcopy` right?

**Comment by joelberkeley** [comment]
> the main usage is to have access to a complete model after each iteration in the BO loop - for diagnostics, recovering from errors etc, right?

yes i believe so. @vpicheny 's the one to ask about that

> what about memory footprint? GPflow models contain data, hopefully data is not really copied for each deepcopy, in case of large datasets with SVGP that could be a lot...

I've implemented `__deepcopy__` for many copied types in trieste. Where the data type is immutable, such as `Dataset`, I've made `__deepcopy__` return `self`, avoiding extra memory usage

> that issue with deepcopying `tf.Module` has been fixed in TF probability 0.12 and we are now on tensorflow-probability>=0.12, so we should be able to remove `module_deepcopy` right?

possibly, but I think I added tests that check it doesn't work

**Comment by hstojic** [comment]
re GPflow - it seems like everything is working fine without `module_deepcopy` function, I have just pushed a PR: #339
