### ISSUE TITLE
Check notebook syntax on CI

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [secondmind-labs/trieste#37]
**Describe the feature you'd like**
As a developer, I want the notebooks to be checked for Jupytext syntax errors on CI, so that I know my changes haven't broken the notebooks.

This is very closely related to #36

**Comment by joelberkeley-secondmind** [comment]
@insysion mentioned:

> Have you looked at any of the pytest notebook plugins? e.g. https://pypi.org/project/pytest-notebook/ and https://pypi.org/project/pytest-ipynb/ Worth noting that I know next to nothing about any of these, just throwing ideas out.

**Comment by alex-treebeard** [comment]
Hey there, just want to add [nbmake](https://github.com/treebeardtech/nbmake) to this list which i've just released. Would love to take any feedback on it.

**Comment by uri-granta** [comment]
Done as part of #36 since the notebooks are all executed when we build the docs.
