### ISSUE TITLE
Removing `models/config.py`?

### ISSUE THREAD

**Issue by hstojic** [secondmind-labs/trieste#373]
I would like to discuss whether our config system is actually useful in its current form, if not perhaps we should dispense with it, simplify the codebase and reduce our maintenance.

After talking with almost everyone, it is not entirely clear why we have `ModelConfig` and were allowing specifying models as a dictionary via `create_model`. Was this aimed at simplifying life for the novice users or at facilitating things for power users that know the modelling toolboxes and trieste wrappers very well?

My best guess is that a user can be ignorant about model and optimizer wrappers, one only needs to specify a GPflow model and our model factory will do the rest - no need to know the names of the wrappers, and no need to handle two objects (first create an Optimizer which is then passed to a model wrapper). For power users, if you know all the arguments to the wrappers I guess this could simplify things a bit. For novice users the issue with this is that you still have to look up the wrappers if you need to pass some additional arguments so you might as well use them (in my view it is also too black-boxy and is not incentivising users to get to know the toolbox). Also, you still need to be quite an expert to set up a model. If we look at our usual examples in the notebooks, building a model requires 5-10 lines of non-trivial GPflow code. A useful config system would take care of building a model as well. 

There is potentially another usage. Configs might facilitate coding up large scale experiments where we compare lots of algorithms. @apaleyes gave an example on how setting the parameters of the experiment could be easier than working with objects directly
```python
basic_config = blah

for params in candidate_param_list:
    basic_config["model_params"] = params
    do_banchmark(basic_config)
```
However, it doesn't seem like anyone was really using configs for this purpose so far (anyone?), so not sure if this is a realistic us case. Perhaps not in a current form and if this would be useful, we could think of extending configs. We could try exploring this with a notebook?

In the discussions there were also mentions of having sensible defaults for (almost) everything so that its easy to set things up and run an BO algorithm for an unexperienced BO user. We should definitely do this but I think this is not relevant for the current config system.

As I see it we have 4 options:
1a. Do nothing for the time being, keep maintaining it until we collect more info on how users use configs (how do we do that though?). Perhaps try making dictionary option possible again.
1b. If we agree that this is a tool for power users, then to reduce chances of confusing novice users we should remove dictionary/model config way of setting up a model from notebooks and write a new notebook aimed at explaining configs, how to use them and when.
2. Remove it and rely on working with model and optimizer wrappers directly. Perhaps focus on making sure we provide sensible defaults wherever we can.
3. Develop configs further, perhaps something where we can configure a whole BO algorithm, both underlying GPflow model, acquisition function, optimization process etc. @avullo might have some useful pointers here.

Any feedback would be much appreciated!
Pointers to config systems in other toolboxes are welcome as well.

**Comment by apaleyes** [comment]
This question might be closely related, or not related at all, to #239 (which is also closely related to benchmarking). There are many ways to decipher "support for experiments", and one of them might be allowing users to declaratively describe their experiments in files. If that's the route Trieste ends up taking for #239 , model configs would need to be developed a bit further (pt 3) but can be natural choice.

Therefore I'd suggest to stick to 1a for now, and focus on #239. If the experiments are implemented without use of model configs, then model configs aren't needed indeed.

**Comment by hstojic** [comment]
I agree, this issue could be related to #239 if we go with option 3, and yes, its still uncertain what form that would take. 
On the other hand, developing configs further might help with setting up a model (those 5-10 lines of GPflow expertise) and would then reduce barriers-to-entry quite a bit.

**Comment by apaleyes** [comment]
Shall we close this then as a no-op for now, and prioritize #239?

**Comment by hstojic** [comment]
I think doing the bare minimum in 1b is needed, so a small PR to clean things up and explain to users how and when to use configs
configs are also less usable since I removed dictionary option, I should find a way to get that back in

**Comment by apaleyes** [comment]
Sounds good!
