### ISSUE TITLE
Make deep gp integ test more stable

### ISSUE THREAD

**Issue by apaleyes** [secondmind-labs/trieste#375]
The `test_two_layer_dgp_optimizer_finds_minima_of_michalewicz_function` test in `test_bayesian_optimization` still fails sometimes. But always comes back when you restart it.

What can we do to make it stable? Since this is the integration test, I propose we reduce the search space to ensure it finds the minimum at `x*`. At the moment it uses `Box([0, 0], [pi, pi])` as is standard for Michalewicz functions. Perhaps for an integration test we could use `Box(x* - [0.5, 0.5], x* + [0.5, 0.5])`.

**Comment by hstojic** [comment]
yes, I noticed as well it sometimes fails, I agree with the suggestion, we could do that - @sebastianober what do you think?

**Comment by apaleyes** [comment]
I've spoken to Sebastian offline prior to creating this issue, and he is happy with that change
