### ISSUE TITLE
Add knowledge gradient acquisition function

### ISSUE THREAD

**Issue by vpicheny** [secondmind-labs/trieste#39]
Implement the approximate knowledge gradient acquisition function as described [this article](http://optimallearning.princeton.edu/Papers/Scott%20Powell%20-%20Knowledge%20gradient%20for%20continuous%20parameters%20February2011.pdf)

An R implementation is available [here](https://rdrr.io/cran/DiceOptim/man/AKG.html)

AKG is designed to tackle single-objective, constraint-free, noisy problems

**Comment by uri-granta** [comment]
@vpicheny Is this still something we're interested in implementing at some point?

**Comment by vpicheny** [comment]
no, I think that we decided against it some time ago
