### ISSUE TITLE
TF compilation causes problems for VGP models

### ISSUE THREAD

**Issue by apaleyes** [secondmind-labs/trieste#406]
**Describe the bug**
TF compilation causes problems for models other than GPR when used with EI

**To reproduce**
To reproduce, we start with the EI notebook: https://secondmind-labs.github.io/trieste/notebooks/expected_improvement.html
In this notebook, replace GRP with VGP, by replacing this code:
```
def build_model(data):
    variance = tf.math.reduce_variance(data.observations)
    kernel = gpflow.kernels.Matern52(variance=variance, lengthscales=[0.2, 0.2])
    prior_scale = tf.cast(1.0, dtype=tf.float64)
    kernel.variance.prior = tfp.distributions.LogNormal(tf.cast(-2.0, dtype=tf.float64), prior_scale)
    kernel.lengthscales.prior = tfp.distributions.LogNormal(tf.math.log(kernel.lengthscales), prior_scale)
    gpr = gpflow.models.GPR(data.astuple(), kernel, noise_variance=1e-5)
    gpflow.set_trainable(gpr.likelihood, False)

    return GPflowModelConfig(**{
        "model": gpr,
        "model_args": {
            "num_kernel_samples": 100,
        },
        "optimizer": gpflow.optimizers.Scipy(),
        "optimizer_args": {
            "minimize_args": {"options": dict(maxiter=100)},
        },
    })
```

with this (the smallest possible change to replace GPR with VGP):
```
def build_model(data):
    variance = tf.math.reduce_variance(data.observations)
    kernel = gpflow.kernels.Matern52(variance=variance, lengthscales=[0.2, 0.2])
    prior_scale = tf.cast(1.0, dtype=tf.float64)
    kernel.variance.prior = tfp.distributions.LogNormal(tf.cast(-2.0, dtype=tf.float64), prior_scale)
    kernel.lengthscales.prior = tfp.distributions.LogNormal(tf.math.log(kernel.lengthscales), prior_scale)
    likelihood = gpflow.likelihoods.Gaussian()
    vgp = gpflow.models.VGP(data.astuple(), kernel, likelihood)

    return GPflowModelConfig(**{
        "model": vgp,
        "optimizer": gpflow.optimizers.Scipy(),
        "optimizer_args": {
            "minimize_args": {"options": dict(maxiter=100)},
        },
    })
```

Now run it and observe the following error:
> tensorflow.python.framework.errors_impl.FailedPreconditionError:  Could not find variable _AnonymousVar18. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Resource localhost/_AnonymousVar18/N10tensorflow3VarE does not exist.

(not pasting full stack trace in interest of readability)

**Expected behaviour**
I would expect the notebook to execute without errors.

**System information**
 - Trieste version: top of develop
 - TensorFlow version: 2.6.0
 - GPflow version: 2.2.1

**"Fixes"**
Not suggesting any of these as fixes, but as evidence that this is a TF compilation problem:

1. If we don't compile EI function call by removing decorator `@tf.function` from it (see [line link](https://github.com/secondmind-labs/trieste/blob/develop/trieste/acquisition/function.py#L249)) the error goes away.
2. If we don't update EI function, and create a new one every time, like we do anyway for most of acquisition functions (to do that replace `function.update` [here](https://github.com/secondmind-labs/trieste/blob/develop/trieste/acquisition/function.py#L220) with `return expected_improvement(model, eta)` as [here](https://github.com/secondmind-labs/trieste/blob/develop/trieste/acquisition/function.py#L201)), the error goes away.

**Comment by apaleyes** [comment]
Tagging @vpicheny who discovered it, @uri-granta and @henrymoss who might have the best opinions on how to fix it.

**Comment by uri-granta** [comment]
Here's a slightly simpler complete test case.

```python
import gpflow
import tensorflow as tf
import trieste

search_space = trieste.space.Box([0, 0], [1, 1])
observer = trieste.objectives.utils.mk_observer(trieste.objectives.scaled_branin)
initial_data = observer(search_space.sample_sobol(5))
variance = tf.math.reduce_variance(initial_data.observations)
kernel = gpflow.kernels.Matern52(variance=variance, lengthscales=[0.2, 0.2])
likelihood = gpflow.likelihoods.Gaussian()
vgp = gpflow.models.VGP(initial_data.astuple(), kernel, likelihood)
model = trieste.models.gpflow.VariationalGaussianProcess(vgp)

class SimpleAcquisitionBuilder(trieste.acquisition.SingleModelAcquisitionBuilder):

    def prepare_acquisition_function(self, model, dataset):

        @tf.function
        def acquisition(x):
            return model.predict(tf.squeeze(x, -2))[0]

        return acquisition

    def update_acquisition_function(self, function, model, dataset):
        return function

bo = trieste.bayesian_optimizer.BayesianOptimizer(observer, search_space)
rule = trieste.acquisition.rule.EfficientGlobalOptimization(SimpleAcquisitionBuilder())
result = bo.optimize(10, initial_data, model, acquisition_rule=rule)
```

Some comments:

1. This seems to be connected to the compiled `model.predict`, which calls through to gfplow's `VGP.predict_f` method.
2. It's specific to VGP (GPR and SVGP both work fine).
3. It's not connected to our wrapping `VGP.num_data` in a property in `VariationalGaussianProcess`, as commenting this out makes no difference.
4. It's not obviously connected to our wrapping `VGP.data` in Variables in `VariationalGaussianProcess`, as at the point it fails those look fine, having been successfully updated with a new observation.
5. It's not obviously connected to the `conditional` Dispatcher in `VGP.predict_f`as that still seems to go through the same object dispatcher despite the type of data changing to be a Variable (the other dispatchers are all on gpflow-specific types).
5. At the point of failure, the compiled acquisition function is being passed a <tf.Tensor: shape=(2000, 1, 2), dtype=float64> and 5 resources. The function definition is impressively verbose (see [eager_function_definition.txt](https://github.com/secondmind-labs/trieste/files/7519603/eager_function_definition.txt)).
6. The full error message is

```python
tensorflow.python.framework.errors_impl.FailedPreconditionError:  Could not find variable _AnonymousVar17.
This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized.
Debug info: container=localhost, status=Not found: Resource localhost/_AnonymousVar17/N10tensorflow3VarE
    does not exist.
[[node BroadcastTo_2/identity/forward/ReadVariableOp (defined at /.pyenv/versions/trieste3/lib/python3.7/
site-packages/tensorflow_probability/python/internal/nest_util.py:278) ]] [Op:__inference_acquisition_63149]
```

which seems to reference the following node:

```
node_def {
  name: "BroadcastTo_2/identity/forward/ReadVariableOp"
  op: "ReadVariableOp"
  input: "shape_4_identity_forward_readvariableop_resource"
  attr {
    key: "dtype"
    value {
      type: DT_DOUBLE
    }
  }
  experimental_debug_info {
    original_node_names: "BroadcastTo_2/identity/forward/ReadVariableOp"
  }
}
```

**Comment by uri-granta** [comment]
[Uploading eager_function_definition.txt…]()

**Comment by uri-granta** [comment]
[eager_function_definition.txt](https://github.com/secondmind-labs/trieste/files/7519603/eager_function_definition.txt)

**Comment by uri-granta** [comment]
So the issue turned out to actually be quite glaring (though it would still be nice to figure out how to link the error message directly to the faulty code): the VGP variational parameters `VGP.m_qu` and `VGP.m_sqrt`, which are stored in gpflow.Parameters, are being being overridden rather than `.assign`ed to like Variables.

Sadly, to be able to assign we need to give them variable shapes, just like we do for the data. However `gpflow.Parameter` doesn't support this. In the linked PR I've hacked a modified version of `gpflow.Parameter` that _does_ support variable shapes, which in turn requires a modified version of `tfp.python.util.TransformedVariable`. This is still tripping up during optimization though, when we appear to try to initialize an all-zero `m_qu` from the dynamic shape, which now fails. If we get this working, at least some of the fix should probably be pushed to gpflow.

While looking at this I also spotted and fixed an issue with using subclasses of VGP models with our `VariationalGaussianProcess` class.

**Comment by uri-granta** [comment]
PS The issue at the moment is inside the Adam optimizer, which I think is trying to initialize the moment vector m. Even if we hack it so it initializes it correctly, then it later complains that m and var have different shapes, since the latter has been updated. I don't know if that's because the optimizer maintains state after we update the m_qu and m_sqrt which no longer matches them?

**Comment by uri-granta** [comment]
PPS At a  lower level, the optimizer is failing to add a slot variable with `OptimizerV2.add_slot` because the m_qu variable now has variable shape. Hacking the assignment of slot_shape from `var.shape` to `array_ops.shape(var)` just postpones the problem to later, when the slot variable and updated m_qu variable no longer have the same shape.
