### ISSUE TITLE
TF errors are not handled gracefully by the BayesianOptimizer

### ISSUE THREAD

**Issue by apaleyes** [secondmind-labs/trieste#415]
**Describe the bug**
As far as I can see from the BayesianOptimizer implementation, it is intended to keep track of the history and, should any error occur during the optimization due to, let's say, numerical instability, it is supposed to catch the error and return most recent optimization state to the user.

However this doesn't happen in case TF error appears, e.g. due to Cholesky decomposition failure.

**To reproduce**
Here is the code that reproduces the failure. Notice crazy high lengthscales, crazy low noise, and `fit_initial_model=False` - these are required to make Cholesky decomposition in TF fail.

```
    num_steps = 2

    search_space = BRANIN_SEARCH_SPACE

    def build_model(data: Dataset) -> GaussianProcessRegression:
        variance = tf.math.reduce_variance(data.observations)
        kernel = gpflow.kernels.Matern52(variance, tf.constant([100000000000000, 100000000000000], tf.float64))
        gpr = gpflow.models.GPR((data.query_points, data.observations), kernel)
        gpr.likelihood.variance = gpflow.base.Parameter(1e-63, transform=gpflow.utilities.positive(lower=1e-64))
        gpflow.utilities.set_trainable(gpr.likelihood, False)
        return GaussianProcessRegression(gpr)

    initial_query_points = search_space.sample(5)
    observer = mk_observer(scaled_branin)
    initial_data = observer(initial_query_points)
    model = build_model(initial_data)

    acquisition_rule = EfficientGlobalOptimization()

    try:
        dataset = (
            BayesianOptimizer(observer, search_space)
            .optimize(num_steps, initial_data, model, acquisition_rule, fit_initial_model=False)
            .try_get_final_dataset()
        )
        print("Handled!")
    except tf.errors.InvalidArgumentError as e:
        print(e)
```

**Expected behaviour**
`"Handled!"` should be printed. But instead error is printed, meaning it wasn't handled by the optimizer's code.

**System information**
 - Python version: 3.7.5
 - Trieste version: Tip of develop
 - TensorFlow version: 2.6.0
 - GPflow version: 2.2.1

**Additional context**
I had a go at fixing it, by replacing this:

    except Exception as error:

with this

    except (Exception, tf.errors.InvalidArgumentError) as error:

in the `BayesianOptimizer.optimize`, but it didn't help - apparently has something to do with the [compilation graph and when it is actually executed](https://github.com/tensorflow/tensorflow/issues/33281).

**Comment by uri-granta** [comment]
This is working as intended. Quoting from the tutorial:

> The optimization loop catches errors so as not to lose progress, which means the optimization loop might not complete and the data from the last step may not exist. Here we’ll handle this crudely by asking for the data regardless, using .try_get_final_datasets(), which will re-raise the error if one did occur.  For a review of how to handle errors systematically, there is a dedicated tutorial.

To handle the error you can write the following instead:

```python
    result, history = (
        BayesianOptimizer(observer, search_space)
        .optimize(num_steps, initial_data, model, acquisition_rule, fit_initial_model=False)
        .astuple()
    )
```

at which point you will find that `result.is_ok` is `False` and `history` contains the initial record and model.

**Comment by apaleyes** [comment]
Ok, so that's me being inattentive with the API. Thanks for the clarification, Uri! At least we know how to trigger cholesky error on demand now.
