### ISSUE TITLE
Tutorial code snippets should be no more than 80 characters wide to avoid drag bars

### ISSUE THREAD

**Issue by uri-granta** [secondmind-labs/trieste#423]
Tutorial code snippets should be no more than 80 characters wide to avoid the ugly drag bars that we currently sometimes have.

We could enforce this by having a different black line-length limit for the docs.

**Comment by hstojic** [comment]
we also get vertical drag bars sometimes when a lot of figures are generated, I find those annoying
perhaps some of these solutions? https://stackoverflow.com/questions/36757301/disable-ipython-notebook-autoscrolling
