### ISSUE TITLE
Quickdocs build not catching issues with notebooks

### ISSUE THREAD

**Issue by apaleyes** [secondmind-labs/trieste#436]
We had a couple of commits that passed the quickdocs build, but then failed the full docs build due to errors in the notebooks' execution: [1](https://github.com/secondmind-labs/trieste/runs/4298063741), [2](https://github.com/secondmind-labs/trieste/runs/4298294070), [3](https://github.com/secondmind-labs/trieste/runs/4299218398), [4](https://github.com/secondmind-labs/trieste/runs/4300219430), [5](https://github.com/secondmind-labs/trieste/runs/4309808577).

We shall consider ways to increase the scope of quickdocs build to be able to catch more of such errors. Ideally without affecting the running time.

**Comment by uri-granta** [comment]
Doesn't seem to be an issue any more.
