### ISSUE TITLE
Logging for the parallel acquisiton function optimizer

### ISSUE THREAD

**Issue by henrymoss** [secondmind-labs/trieste#440]
e.g. which k was it that yielded the best solution, what were the values and points in all k runs, did we enter the recovery runs etc ?

I think it would be useful for monitoring, e.g. to spot whether you might need to decrease/increase the number of runs, or if you are consistently entering recovery runs that something might be off

**Comment by uri-granta** [comment]
Looking at this as part of https://github.com/secondmind-labs/trieste/pull/577. Can you clarify what precisely you'd liked logged?

At the moment all I've got is a text log for each optimization step where the recovery runs were triggered:

> "Acquisition function optimization failed after 10 optimization runs, requiring recovery runs"
