### ISSUE TITLE
Seperate model interfaces for cleaner type checks

### ISSUE THREAD

**Issue by henrymoss** [secondmind-labs/trieste#445]
We have a `FantasyPredictModel` interface, it would be nice to have similar interfaces for `TrajecotrySamplerModel`, `ReparamSamplerModel` etc .....

We can then have more informative type checking for acquisitions functions and samplers that require access to specific methods.

**Comment by hstojic** [comment]
this has been addressed by @uri-granta we can close this now, right?

**Comment by uri-granta** [comment]
Yes, this has now been done.
