### ISSUE TITLE
Integration tests for greedy batch methods

### ISSUE THREAD

**Issue by vpicheny** [secondmind-labs/trieste#446]
We have two methods without integration tests: `LocalPenalisation` and `Fantasizer`. We should have integration tests that show for instance that `ExpectedImprovement` performance doesn't degrade significantly when paired with either greedy method. Another integration test for `Fantasizer` should be in the async batch setting.

**Comment by uri-granta** [comment]
There are now 5 (soon to be 6) LocalPenalization integration tests and one Fantasizer test. Ok to close?
