### ISSUE TITLE
Tutorials of how to use and extend toolbox functionality

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [secondmind-labs/trieste#48]
**Describe the feature you'd like**
As a user, I would like tutorials that explain how to work with the various pieces of functionality in trieste, such as examples of how to build my own acquisition function or rule, how to use my own model.

These can be links in the docs to existing tutorials that do these things, but in cases where there are no tutorials containing these, either create a specific ticket for each tutorial, or make the tutorial

**Comment by vpicheny** [comment]
One possibility is to have a FAQ page with links to the existing notebooks.
I would suggest to start with the FAQ and see how much coverage we have. Suggestion in next comment.

**Comment by vpicheny** [comment]
- how does trieste work with multiple models?
- how can I use my own acquisition function?
- how can I use my own acquisition rule?
- how can I specify a different model training routine?
- how can I specify my own acquisition function optimizer? (not as important)
- how can I plug in my specific gpflow model?

**Comment by joelberkeley** [comment]
@vpicheny note i've already started on this (you can see linked PRs on the RHS), and I'm doing pretty much what you've suggested. I'm just having difficulty making links to notebook subheadings. Apparently James L has also been trying this to no avail
