### ISSUE TITLE
PredictiveVariance scales poorly

### ISSUE THREAD

**Issue by hstojic** [secondmind-labs/trieste#495]
`PredictiveVariance` is not scaling well enough, e.g. already with datasets of medium size, about 200 points in 6 dim hartmann problem my computer runs out of memory and process gets killed

I think `predict_joint` call in `PredictiveVariance` is the culprit, single call is fine for the data sizes we deal with here, you really need to increase the data size a lot to hit the memory issue, but I suspect I get it even for smaller datasets because our acquisition optimizer calls it in parallel

I'm not sure whether there is any solution to this, perhaps it simply cannot be used with a lot of data and we put a warning in the docs, some other ideas:
1. warning as above + @uri-granta idea to put the acquisition optimizer in a serial mode (looking into this right now, @henrymoss?), so the memory issue is hit later on + do it in the notebook as well
2. for batch=1, call `predict` and just do max var, there is no need for joint call here, right (@vpicheny @satrialoka)? that would make the function much more efficient at least in this case 

any other ideas?

**Comment by uri-granta** [comment]
Regarding 1, henry noted that the memory usage is as likely to be an issue in the initial acquisition function evaluation as it is during the parallel optimizations. One way to reduce it is to allow acquisition function evaluations to be batched when they're being evaluated regardless of parallelisation. See linked draft PR for a start on this.

**Comment by hstojic** [comment]
> Regarding 1, henry noted that the memory usage is as likely to be an issue in the initial acquisition function evaluation as it is during the parallel optimizations. One way to reduce it is to allow acquisition function evaluations to be batched when they're being evaluated regardless of parallelisation. See linked draft PR for a start on this.

That's a neat idea!
