### ISSUE TITLE
ExpectedFeasibility cannot be used with LocalPenalization

### ISSUE THREAD

**Issue by hstojic** [secondmind-labs/trieste#503]
As pointed out by @vpicheny this doesn't work out of the box because EF can return negative values while LP only works with positive acquisition functions (such as EI). The simple hack is to transform EF using log(1 + exp(x)).

I think this transformation should not affect the acq function, we would only add a small computational overhead, so I would vote for modifying the EF

**Comment by vpicheny** [comment]
Would it be possible instead of having a `MakePositive` method? so that we would write something like:
`acq = MakePositive(ExpectedFeasibility)`

that way, the trick is available for all methods that need it, e.g. UCB.

**Comment by hstojic** [comment]
good idea, let's do that
