### ISSUE TITLE
Model unit tests are impractically slow

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [secondmind-labs/trieste#51]
**Describe the bug**
Running the model unit tests via `tox -e tests` takes much longer than unit tests should do

**System information**
 - OS: Ubuntu 18.04
 - Python version: 3.7
 - Trieste version: develop commit 3e5703511d4d510da308910b23da5383ef0079b9
 - TensorFlow version: 2.3.1
 - GPflow version: 2.1.3

**Comment by uri-granta** [comment]
FYI run `task tests` now returns the slowest running tests. Also, it's possible to mark slow-running tests with @pytest.mark.slow, meaning they only get run after merging to develop.

**Comment by uri-granta** [comment]
CI test runtime is no longer an issue, due to parallelisation and splitting off slower running tests.
