### ISSUE TITLE
out of memory errors with new caching

### ISSUE THREAD

**Issue by hstojic** [secondmind-labs/trieste#524]
using https://github.com/secondmind-labs/trieste/pull/523 branch, when calling predict with GPR model on a large number of query points (e.g. 100000) we run out of memory quickly, batching predictions resolves it (see [here](https://github.com/Prowler-io/pio_bench/blob/1838fa843020780cf9d231c4716d4c4847d20e97/src/pio_bench/model/regression/gpflow_gaussian.py#L17) for an example), but before there was no issue with predictions on such data sizes

**Comment by vpicheny** [comment]
Here is a minimal example of this happening:

```
import tensorflow as tf
from trieste.models.gpflow import GaussianProcessRegression
from gpflow.models import GPR
from gpflow.kernels import Matern52

X = tf.random.uniform((5, 1), minval=0., maxval=1., dtype=tf.float64)
Y = tf.random.uniform((5, 1), minval=0., maxval=1., dtype=tf.float64)

gpflow_model = GPR(data=(X, Y), kernel=Matern52())
model = GaussianProcessRegression(gpflow_model)

num_samples = 50000
X = tf.random.uniform((num_samples, 1), minval=0., maxval=1., dtype=tf.float64)

m, v = model.predict(X)
```

**Comment by uri-granta** [comment]
The issue seems to be the `GPRPosterior._conditional_with_precompute` method in GPFlow. When calculating the diagonal covariance matrix it uses
```python
tf.linalg.diag_part(Knm @ Qinv @ Kmn)
```
which results in an intermediate 50000x50000 matrix. I think we can do this more space efficiently with
```python
tf.einsum('ij,jk,ki->i', Knm, Qinv, Kmn)
```

This would have to be changed in GPFlow; I don't think we can easily work around it in trieste. @jesnie ?

**Comment by jesnie** [comment]
Thanks for debugging this. Seems like a nice / easy fix. Can you send me a PR for GPflow?

Makes me wonder how many places we do something similar and that can be optimised? It is pretty wasteful to compute a full matrix product, and then only use the diagonal.

**Comment by hstojic** [comment]
@uri-granta this has been done, right?

**Comment by hstojic** [comment]
This has been sorted out in gpflow 2.5.2 which we have switched to in #555
