### ISSUE TITLE
 cheap-to-evaluate constraint

### ISSUE THREAD

**Issue by satrialoka** [secondmind-labs/trieste#537]
**Describe the feature you'd like**
I want functionality for using cheap-to-evaluate-constraint in Trieste directly without modeling it using a GP.

**Is your feature request related to a problem? Please describe.**
Sometimes we had a closed-form formula of our constraint which will be faster and more accurate to use as it is rather than model it as a GP. 

**Describe alternatives you've considered**
One of the approaches is utilizing the scipy optimizer such as [SLSQP](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-slsqp.html)(gradient-based) and [COBYLA](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-cobyla.html)(gradient-free), by feeding the cheap constraint directly to the acquisition function optimizer. 

**Additional context**
Currently, Trieste 0.10.0 [only supports LBFGSB optimizer](https://github.com/secondmind-labs/trieste/blob/13131d093ecc447b8becf1003fcfd58e4b4185d0/trieste/acquisition/optimizer.py#L494), it might be nice if we can change the choice of optimizer by using optimizer args without modifying the acquisition optimizer function.

I was using this approach on the older version of Trieste, the problem that might arise is the starting point of the MC stage in the acquisition optimizer will be unfeasible cheap-constraint wise. I was removing the unfeasible points using `tf.boolean_mask` to tackle this problem.

Other concern is, the cheap-constraint might be too strict and makes the BO not exploring some areas which might be important for the GPs of the objectives and expensive constraints.

**Comment by uri-granta** [comment]
Explicit constraints are now supported (#656, #660, #664) as described at https://secondmind-labs.github.io/trieste/develop/notebooks/explicit_constraints.html. Is it ok to close this ticket?

**Comment by satrialoka** [comment]
Nice! Sure!
