### ISSUE TITLE
Decoupled trajectory samplers for GPflow models do not use mean function

### ISSUE THREAD

**Issue by sebastianober** [secondmind-labs/trieste#543]
**Describe the bug**
The decoupled trajectory samplers for GP models do not make use of the model's mean function. This is fine for e.g. a constant mean function, but in the case of e.g. a linear mean function the acquisition rule would not select the correct point.

**Expected behaviour**
This should be a fairly minor modification - all that needs to be changed is that the mean function needs to be added to the current trajectories. This should also be checked for other trajectory samplers.

**Comment by hstojic** [comment]
I think this was done in #556 , we can close this one right?

**Comment by hstojic** [comment]
yep, done in #556
