### ISSUE TITLE
Convenient API when using one model and dataset

### ISSUE THREAD

**Issue by joelberkeley** [secondmind-labs/trieste#55]
As a user, I want an easy, intuitive, and safe way to use the toolbox when my problem is only for one model and dataset.

At the moment, users must use a single-entry dictionary, which is inconvenient and ugly boilerplate.

We have a number of candidate designs to achieve this. They are listed below. The summaries are a work in progress

**Comment by joelberkeley** [comment]
**Option 1: Add a single-model version of anything that works with only one model** (see PR #50 )

For

- It's unambiguous
- It's type safe
- The types are simple

Against

- It involves a fair bit of duplication, mostly centred around the optimizer and the acquisition rules

**Comment by joelberkeley** [comment]
**Option 2a: Wrap models and data in an interface common to both single and multi-model setups** (see PR #49 )

For

- It's terse (little to no duplication)
- It's mostly type safe
- There's a single entrypoint for everything

Against

- Python doesn't natively support the higher-kinded types needed to write the types: we need a third party library (which is in beta). Consequently:
  - this will make it hard for most users and contributors to understand the types
  - there are already limitations to how well the library integrates with the Python stdlib's type hints
  - there may be bugs in the third party library

**Comment by joelberkeley** [comment]
**Option 2b: Like 2a, but instead of using higher-kinded types, break type safety and use error handling.**

For

- It's terse (little to no duplication)
- There's a single entrypoint for everything

Against

- It's not type safe (frequently breaks LSP)

**Comment by joelberkeley** [comment]
**Option 2c: Like 2a, but parametrize over single vs multiple datasets separately from models.**

It's not clear if the `Grouping` interface would be expressible here, so we may need to resort to `Union[One[T], Many[T]]`

For

  - todo

Against:

  - Requires separate wrappers for every type of contents: `Dataset`, `ProbabilisticModel`, `ModelSpec`

**Comment by joelberkeley** [comment]
@uri-granta I'm curious - did you manage to solve this?

**Comment by uri-granta** [comment]
> @uri-granta I'm curious - did you manage to solve this?

Yes (at least well enough to make everyone happy). See linked PR and comments at https://github.com/secondmind-labs/trieste/pull/252.
