### ISSUE TITLE
Seed argument on space's random sample method

### ISSUE THREAD

**Issue by satrialoka** [secondmind-labs/trieste#560]
**Describe the feature you'd like**
I would like to have set seed functionality in `Box` and `DiscreteSearchSpace`'s `.sample()` method 

**Is your feature request related to a problem? Please describe.**
This will help reproducibility for a research purposes

**Describe alternatives you've considered**
Simply add seed argument to the `.sample()` method  and pass it to the `tf.random` function that generate the random points

**Comment by henrymoss** [comment]
Sounds good. Fancy submitting a PR @satrialoka ?

**Comment by satrialoka** [comment]
Sure!
