### ISSUE TITLE
`TaggedProductSearchSpace` cannot be created from empty `TaggedProductSearchSpace`

### ISSUE THREAD

**Issue by Corwinpro** [secondmind-labs/trieste#566]
**Describe the bug**

When creating a `TaggedProductSearchSpace` from `TaggedProductSearchSpace`s that were created in an inconsistent way, this

https://github.com/secondmind-labs/trieste/blob/f3a9636ce42419b0ad4f766d5eef60f023c7211a/trieste/space.py#L488

fails.

**To reproduce**
Steps to reproduce the behaviour:

```python
>>> from trieste.space import Box, TaggedProductSearchSpace
>>> space_A = Box([-1, -2], [2, 3])
>>> tgpss_A = TaggedProductSearchSpace(spaces=[space_A], tags=["A"])
>>> tgpss_B = TaggedProductSearchSpace(spaces=[], tags=[])
>>> tgpss_C = TaggedProductSearchSpace(spaces=[tgpss_A, tgpss_B], tags=["AA", "BB"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pyenvs/trieste-dev/trieste-py38/lib/python3.8/site-packages/trieste/space.py", line 488, in __init__
    self._subspace_starting_indices = dict(zip(tags, tf.cumsum(subspace_sizes, exclusive=True)))
  File "/home/pyenvs/trieste-dev/trieste-py38/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/pyenvs/trieste-dev/trieste-py38/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7164, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute Pack as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:Pack] name: x
```

**Expected behaviour**

This should not raise.

**System information**
 - OS: Ubuntu 20.04
 - Python version: 3.7 / 3.8
 - Trieste version: 0.11.0
 - TensorFlow version: 2.4 and later
 - GPflow version: 2.5.2

**Additional context**

This happens because `tgpss_B = TaggedProductSearchSpace(spaces=[], tags=[])` uses this code in an inconsistent way:

https://github.com/secondmind-labs/trieste/blob/f3a9636ce42419b0ad4f766d5eef60f023c7211a/trieste/space.py#L490

For `spaces=[]` this works out to to `tf.reduce_sum([])` which yields `float32`. In the non-empty case (`tgpss_A` as example) the return value is `int32`. Then, `tf.cumsum(subspace_sizes, exclusive=True)` in `tgpss_C.__init__` fails to combine both types.

This is due to backwards incompatible change in #513 that stopped converting `self._dimension` to `int` but returns `TensorType` directly.

**Comment by uri-granta** [comment]
Fixed this in #578. Thanks for spotting it and raising an issue!
