### ISSUE TITLE
Comprehensive unit tests

### ISSUE THREAD

**Issue by joelberkeley** [secondmind-labs/trieste#57]
While everything has _some_ level of testing, unit test coverage for the toolbox is not comprehensive. Missing tests are mostly either unhappy path tests incl. error handling, or integration tests used instead of unit tests.

The first task is to go through the code, look at the tests, and check what already has comprehensive test coverage.

Comprehensive unit tests exist for (list updated as tests are checked/added):

- acquisition
  - [x] combination #57
  - function
    - [x] mes (except for full functional form ... see #52 )
    - [x] everything except mes #62 (note we need to update the `QuadraticMeanAndRBFKernel` utility to have non-trivial minimum and variance, and update the tests respectively, for these to be good tests, see #65 )
  - rule
    - [ ] EfficientGlobalOptimization
    - [ ] ThompsonSampling
    - [ ] TrustRegion (rather than testing this more, we could pull it out into a separate thing and the current tests will cover it, and then we'll also get the benefit of using it everywhere)
- models
  - [ ] config
  - [ ] model_interfaces
  - [ ] optimizer
- utils
  - [x] misc
  - [x] objectives
  - [ ] pareto
- [x] bayesian_optimizer #17 
- [x] data #60
- [x] observer #58
- [x] space #59 #80 
- [x] type

**Comment by uri-granta** [comment]
Unit test coverage has been improved and we now track code coverage. More work to be done here but this issue is no longer useful for tracking it.
