### ISSUE TITLE
model optimization history is not saved for gpflow models?

### ISSUE THREAD

**Issue by hstojic** [secondmind-labs/trieste#617]
needs to be checked - e.g. keras and deep GPs attach a history object to the model after model fitting

**Comment by uri-granta** [comment]
Since there is no mention of optimization history in the [gpflow documentation](https://gpflow.github.io/GPflow/2.5.2/search.html?q=history#), suggest closing this and raising a gpflow issue instead.

**Comment by uri-granta** [comment]
Actually this might be most easily fixable in trieste (using step_callbacks) so reopening.
