### ISSUE TITLE
Ensemble trajectories test is fragile and has been skipped

### ISSUE THREAD

**Issue by khurram-ghani** [secondmind-labs/trieste#666]
The test `test_ensemble_trajectory_sampler_is_not_too_deterministic` in `tests/unit/models/keras/test_sampler.py` is failing checks (_tests_latest_) for unrelated changes. The state of 2 trajectories is expected to be different, but isn't in the failure case. The test has been skipped for now.

One possible solution suggested by @uri-granta:
"increase the ensemble size of the models in the test (currently _ENSEMBLE_SIZE * 2 but we could bump it to 20) which might decrease the likelihood of the two trajectories being the same by chance."

**Comment by uri-granta** [comment]
Fixed by https://github.com/secondmind-labs/trieste/pull/682
