### ISSUE TITLE
GPflow wrapper update may be incompatible with tf.function()

### ISSUE THREAD

**Issue by st--** [secondmind-labs/trieste#70]
As mentioned on https://github.com/secondmind-labs/trieste/pull/54, there might be an issue with the current way of how Trieste updates data in GPflow models when you want to use `tf.function` to speed up the prediction step (currently, Trieste only uses `tf.function` for model optimization, and relies on eager mode for predictions).

VariationalGaussianProcess.update() sets the model's `data` attribute to the new (X, Y) tuple. However, if model.predict_f() is wrapped in tf.function(), it will store the values of (X, Y) when first called in the cached graph.
To enable data update with tf.function(), model.data must be set to a tuple of `tf.Variable`s, which are then .assign()ed rather than overwritten in VariationalGaussianProcess.update().

**Comment by joelberkeley** [comment]
@st-- i notice the `.num_data` also needs updating for vgp and svgp, but that's a GPflow attribute of type `int`, and it's not possible for trieste to make this a Variable. Is this right? Is there a recommended way to do this for vpg and svgp?

**Comment by st--** [comment]
What would stop you from making it a variable? You can just do `SVGP(kernel, likelihood, ..., num_data=tf.Variable(123))`? Or after model creation `model.num_data = tf.Variable(model.num_data)`?

**Comment by joelberkeley** [comment]
nothing in that context. I was thinking of the case where there's no opportunity to do so outside of a `tf.function`

**Comment by joelberkeley** [comment]
i guess it depends where the `@tf.function` is. If it's on the `update` then I can see that could fix it. Is modifying it to `Variable` the standard approach?

**Comment by joelberkeley** [comment]
would it be appropriate to change GPflow to make things that may be updated during the model lifecycle to `tf.Variable(x, trainable=False)`?

**Comment by uri-granta** [comment]
I'm currently looking at this (see #271) and am hitting an issue with updating the VGP wrapper. Putting `model.data` in two variables works fine, but putting `model.num_data` in a variable causes the `elbo` method to fail when it tries to execute `tf.eye(self.num_data, dtype=default_float())`, claiming the `self.num_data` isn't an integer. Any idea if there's a way round this? @johnamcleod

**Comment by johnamcleod** [comment]
>  `model.num_data` in a variable causes the `elbo` method to fail 

Unfortunately the `tf.eye` function only supports `Tensor`s, Python `Integral` and `np.integer` types for the first input. If none of those work with `tf.function` you could consider creating a subclass of the VGP model in Trieste to turn the `num_data` attribute into a `@property`. Then it could be dynamically calculated from the size of the Xdata variable. If that works we could incorporate it into GPflow.

**Comment by uri-granta** [comment]
This is now correctly handled in the trieste wrappers.
