### ISSUE TITLE
I have installed greenlet manually, but it not found.

### ISSUE THREAD

**Issue by firefox1900** [secondmind-labs/trieste#704]
TREGO\lib\site-packages\greenlet\__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ModuleNotFoundError: No module named 'greenlet._greenlet'

**Comment by uri-granta** [comment]
Did you install the module with `pip3 install greenlet`?

**Comment by uri-granta** [comment]
Is this still an issue?

**Comment by uri-granta** [comment]
Closing for now, but feel free to reopen if it's still a problem!
