### ISSUE TITLE
Feasible sets tutorial file too big

### ISSUE THREAD

**Issue by uri-granta** [secondmind-labs/trieste#717]
**Describe the bug**
The feasible sets notebooks generated for the docs are 28MB each, which is adding up quickly over time. We should make these smaller, and probably backport the change to reduce the repo size.

**To reproduce**
Steps to reproduce the behaviour:
1. See the feasible_sets.html file in the gh-pages-history branch

**Comment by hstojic** [comment]
how to test that exactly, `tox -e docs` and check the files, right?
