### ISSUE TITLE
Configurable optimizer history size

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [secondmind-labs/trieste#87]
**Describe the feature you'd like**
As a user, I want to be able to configure the history size so that I can track state with minimal memory footprint. For example "save only the 5 latest steps"

This could be implemented by changing `track_state` to an argument `max_history_size: Optional[int]` and using a `collections.deque`. If it would make for a simple user interface, we could then convert the `deque` to a list before returning it

**Comment by uri-granta** [comment]
Since history can now be saved to disk rather than stored in memory (using the `track_path` argument) there is no longer any real need for this.
