### ISSUE TITLE
Write a technical report for trieste

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [secondmind-labs/trieste#89]
As a contributor, I want to publish a technical report to demonstrate and advertise what trieste has to offer as a cutting edge Bayesian optimization toolbox, to increase adoption, showcase Secondmind's research capability, and probably more.

As a user, I want a technical report to gain a deeper insight into what trieste is capable of, how to use it, and why it was designed as it was.

**Comment by joelberkeley-secondmind** [comment]
for those with Secondmind access, here is a thread from someone who'd like a technical report and why https://secondmind-ai.slack.com/archives/CJRFFHBAN/p1586340450003500

**Comment by uri-granta** [comment]
Closing as we now have https://arxiv.org/abs/2302.08436 (linked to from README.md).
