### ISSUE TITLE
Ensure compatibility with tf.function

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [secondmind-labs/trieste#90]
**Describe the feature you'd like**
As a user, I want to be able to use `tf.function` where appropriate with confidence that the code will work, so that I can improve the performance where possible, especially in production.

**Is your feature request related to a problem? Please describe.**
`tf.function` has a number of gotchas, some of which are outlined in Google's [`tf.function` summary](https://www.tensorflow.org/guide/function#python_side_effects). These need to be avoided throughout the codebase.

Most of the code uses tensorflow ops (as opposed to e.g. numpy ops), but the models are mutable so those will need particular attention.

**Comment by joelberkeley-secondmind** [comment]
more detailed description of `tf.function` limitations https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md and SO question where I got that link https://stackoverflow.com/questions/59847045/should-i-use-tf-function-for-all-functions

**Comment by joelberkeley-secondmind** [comment]
#70 covers one specific related gotcha in the models

**Comment by joelberkeley** [comment]
Another point here is `tf.print`. This is only needed within compiled code. However, it's used in the main optimizer, which also uses `try: except:` which isn't compatible with `tf.function`

**Comment by joelberkeley-secondmind** [comment]
Another gotcha: creating `tf.Variable` inside a function. We do this in the acquisition optimizer (and perhaps the reparametrization trick). See [this issue](https://github.com/Prowler-io/bayesian-optimization/issues/92) for why this is problematic

#74 has a fix for the acquisition optimizer

**Comment by uri-granta** [comment]
This has now been addressed in a number of PRs. Any remaining issues (e.g. regarding handling exceptions) are covered by more specific issues.
